### ISSUE TITLE
data loading on Mac appears to be broken

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/org.caleydo.view.lineup#1]
When I click on the "Load Data" menu item it gets highlighted, but nothing else happens.

![screen shot 2013-08-15 at 9 32 54 pm](https://f.cloud.github.com/assets/1216518/973004/fe4ba224-0613-11e3-9cf3-30ab306a582d.png)

**Comment by sgratzl** [comment]
using what: the lasted build from the website, starting from eclipse,...

**Comment by sgratzl** [comment]
-> wrong repository, see Caleydo/org.caleydo.vis.lineup.demos#2

this repository contains the generic lineup view for Caleydo, which can create rankings based on data domains
