### ISSUE TITLE
Allow to perform an "or" filter

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.view.lineup#6]
currently two filter will be "and"ed. It might be interesting to perform an "or" instead

**Comment by sgratzl** [comment]
problems: 
- how to highlight matches -> in the and-case it justs the found rows
- performance -> currently just the remaining elements will be checked, in the or case all "invalid" elements needs to be checked. 
- should and/or be combineable -> how to select the priority: `A and B or C` is not defined.

**Comment by alexsb** [comment]
Highlighting: draw a selection color box around the cell, keep the row selected. 
Performance: will that be a problem
Combinations: I don't think that's necessary. For the GUI input I'd say we only need an OR
