### ISSUE TITLE
Shade bars that are below 0 in the input data range

### ISSUE THREAD

**Issue by alexsb** [Caleydo/org.caleydo.view.lineup#9]
To better deal with negative values, we should shade all bars that are below 0 in the input data range.

**Comment by sgratzl** [comment]
shading with a dashing pattern is already used for encoding "non trivial mappings"

**Comment by sgratzl** [comment]
stippled border for "inferred" values

**Comment by alexsb** [comment]
Cross-hatching?

**Comment by sgratzl** [comment]
inverted hatching:
![one_way](https://cloud.githubusercontent.com/assets/4129778/8234029/e2787388-15d9-11e5-9b17-2108b557bb42.png)

crossed hatching - as suggested
![cross](https://cloud.githubusercontent.com/assets/4129778/8234028/e2762ba0-15d9-11e5-8fcf-dcbabdfeb69d.png)

**Comment by alexsb** [comment]
I think that works, what do you think?
